# Generated by Django 5.1.2 on 2024-12-12 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('img', models.ImageField(blank=True, upload_to='')),
                ('text', models.TextField()),
                ('title2', models.CharField(max_length=200)),
                ('text2', models.TextField()),
            ],
        ),
    ]
